import type { Problem } from './types';

export const PROBLEMS: Problem[] = [
  {
    id: 'two-sum',
    title: '1. Two Sum',
    difficulty: 'Easy',
    tags: ['Array', 'Hash Table'],
    description: 'Given an array of integers `nums` and an integer `target`, return *indices of the two numbers such that they add up to `target`*.\n\nYou may assume that each input would have **exactly one solution**, and you may not use the same element twice.\n\nYou can return the answer in any order.',
    examples: [
      { input: 'nums = [2,7,11,15], target = 9', output: '[0,1]', explanation: 'Because nums[0] + nums[1] == 9, we return [0, 1].' },
      { input: 'nums = [3,2,4], target = 6', output: '[1,2]' },
      { input: 'nums = [3,3], target = 6', output: '[0,1]' },
    ],
    constraints: ['2 ≤ nums.length ≤ 10^4', '-10^9 ≤ nums[i] ≤ 10^9', '-10^9 ≤ target ≤ 10^9', 'Only one valid answer exists.'],
    templates: {
      python: 'class Solution:\n    def twoSum(self, nums: list[int], target: int) -> list[int]:\n        pass',
      javascript: 'function twoSum(nums, target) {\n  // your code here\n}',
      typescript: 'function twoSum(nums: number[], target: number): number[] {\n  // your code here\n}',
      java: 'class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        // your code here\n        return new int[]{};\n    }\n}',
      cpp: 'class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        // your code here\n        return {};\n    }\n};',
      go: 'func twoSum(nums []int, target int) []int {\n    // your code here\n    return nil\n}',
      rust: 'impl Solution {\n    pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32> {\n        // your code here\n        vec![]\n    }\n}',
    },
    hints: [
      { tier: 1, label: 'Conceptual', content: 'Think about what value you need to find for each element to reach the target.' },
      { tier: 2, label: 'Approach', content: 'A hash map can store previously seen values and their indices for O(1) lookups.' },
      { tier: 3, label: 'Pseudocode', content: 'For each num: complement = target - num. If complement in map, return [map[complement], i]. Else map[num] = i.' },
    ],
  },
  {
    id: 'valid-parentheses',
    title: '2. Valid Parentheses',
    difficulty: 'Easy',
    tags: ['String', 'Stack'],
    description: 'Given a string `s` containing just the characters `(`, `)`, `{`, `}`, `[` and `]`, determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.',
    examples: [
      { input: 's = "()"', output: 'true' },
      { input: 's = "()[]{}"', output: 'true' },
      { input: 's = "(]"', output: 'false' },
      { input: 's = "{[]}"', output: 'true' },
    ],
    constraints: ['1 ≤ s.length ≤ 10^4', 's consists of parentheses only \'()[]{}\''],
    templates: {
      python: 'class Solution:\n    def isValid(self, s: str) -> bool:\n        pass',
      javascript: 'function isValid(s) {\n  // your code here\n}',
      typescript: 'function isValid(s: string): boolean {\n  // your code here\n}',
      java: 'class Solution {\n    public boolean isValid(String s) {\n        // your code here\n        return false;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    bool isValid(string s) {\n        // your code here\n        return false;\n    }\n};',
      go: 'func isValid(s string) bool {\n    // your code here\n    return false\n}',
      rust: 'impl Solution {\n    pub fn is_valid(s: String) -> bool {\n        // your code here\n        false\n    }\n}',
    },
    hints: [
      { tier: 1, label: 'Conceptual', content: 'Think about using a stack-based approach to match opening and closing brackets.' },
      { tier: 2, label: 'Approach', content: 'Push opening brackets onto a stack. For closing brackets, check if the top of the stack matches.' },
      { tier: 3, label: 'Pseudocode', content: 'Use a map of closing→opening. For each char: if opening, push. If closing, pop and check match. Return stack empty.' },
    ],
  },
  {
    id: 'best-time-buy-sell',
    title: '3. Best Time to Buy and Sell Stock',
    difficulty: 'Easy',
    tags: ['Array', 'Dynamic Programming'],
    description: 'You are given an array `prices` where `prices[i]` is the price of a given stock on the i-th day.\n\nYou want to maximize your profit by choosing a **single day** to buy one stock and choosing a **different day in the future** to sell that stock.\n\nReturn the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return `0`.',
    examples: [
      { input: 'prices = [7,1,5,3,6,4]', output: '5', explanation: 'Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.' },
      { input: 'prices = [7,6,4,3,1]', output: '0', explanation: 'No profitable transaction is possible.' },
      { input: 'prices = [1,2]', output: '1' },
    ],
    constraints: ['1 ≤ prices.length ≤ 10^5', '0 ≤ prices[i] ≤ 10^4'],
    templates: {
      python: 'class Solution:\n    def maxProfit(self, prices: list[int]) -> int:\n        pass',
      javascript: 'function maxProfit(prices) {\n  // your code here\n}',
      typescript: 'function maxProfit(prices: number[]): number {\n  // your code here\n}',
      java: 'class Solution {\n    public int maxProfit(int[] prices) {\n        // your code here\n        return 0;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    int maxProfit(vector<int>& prices) {\n        // your code here\n        return 0;\n    }\n};',
      go: 'func maxProfit(prices []int) int {\n    // your code here\n    return 0\n}',
      rust: 'impl Solution {\n    pub fn max_profit(prices: Vec<i32>) -> i32 {\n        // your code here\n        0\n    }\n}',
    },
    hints: [
      { tier: 1, label: 'Conceptual', content: 'Track the minimum price seen so far as you iterate.' },
      { tier: 2, label: 'Approach', content: 'For each price, calculate the profit if selling today. Update max profit and min price.' },
      { tier: 3, label: 'Pseudocode', content: 'min_price = inf, max_profit = 0. For each price: max_profit = max(max_profit, price - min_price). min_price = min(min_price, price).' },
    ],
  },
  {
    id: 'longest-substring',
    title: '4. Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    tags: ['String', 'Sliding Window', 'Hash Table'],
    description: 'Given a string `s`, find the length of the **longest substring** without repeating characters.',
    examples: [
      { input: 's = "abcabcbb"', output: '3', explanation: 'The answer is "abc", with the length of 3.' },
      { input: 's = "bbbbb"', output: '1', explanation: 'The answer is "b", with the length of 1.' },
      { input: 's = "pwwkew"', output: '3', explanation: 'The answer is "wke", with the length of 3.' },
      { input: 's = ""', output: '0' },
    ],
    constraints: ['0 ≤ s.length ≤ 5 * 10^4', 's consists of English letters, digits, symbols and spaces.'],
    templates: {
      python: 'class Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:\n        pass',
      javascript: 'function lengthOfLongestSubstring(s) {\n  // your code here\n}',
      typescript: 'function lengthOfLongestSubstring(s: string): number {\n  // your code here\n}',
      java: 'class Solution {\n    public int lengthOfLongestSubstring(String s) {\n        // your code here\n        return 0;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    int lengthOfLongestSubstring(string s) {\n        // your code here\n        return 0;\n    }\n};',
      go: 'func lengthOfLongestSubstring(s string) int {\n    // your code here\n    return 0\n}',
      rust: 'impl Solution {\n    pub fn length_of_longest_substring(s: String) -> i32 {\n        // your code here\n        0\n    }\n}',
    },
    hints: [
      { tier: 1, label: 'Conceptual', content: 'Use a sliding window to track the current substring without repeats.' },
      { tier: 2, label: 'Approach', content: 'Maintain a set/map of characters in the current window. Shrink from the left when a duplicate is found.' },
      { tier: 3, label: 'Pseudocode', content: 'Use two pointers (left, right). Expand right, if char in set, remove chars from left until no duplicate. Track max length.' },
    ],
  },
  {
    id: 'container-with-most-water',
    title: '5. Container With Most Water',
    difficulty: 'Medium',
    tags: ['Array', 'Two Pointers', 'Greedy'],
    description: 'You are given an integer array `height` of length `n`. There are `n` vertical lines drawn such that the two endpoints of the i-th line are `(i, 0)` and `(i, height[i])`.\n\nFind two lines that together with the x-axis form a container, such that the container contains the most water.\n\nReturn the maximum amount of water a container can store.',
    examples: [
      { input: 'height = [1,8,6,2,5,4,8,3,7]', output: '49' },
      { input: 'height = [1,1]', output: '1' },
      { input: 'height = [4,3,2,1,4]', output: '16' },
    ],
    constraints: ['n == height.length', '2 ≤ n ≤ 10^5', '0 ≤ height[i] ≤ 10^4'],
    templates: {
      python: 'class Solution:\n    def maxArea(self, height: list[int]) -> int:\n        pass',
      javascript: 'function maxArea(height) {\n  // your code here\n}',
      typescript: 'function maxArea(height: number[]): number {\n  // your code here\n}',
      java: 'class Solution {\n    public int maxArea(int[] height) {\n        // your code here\n        return 0;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    int maxArea(vector<int>& height) {\n        // your code here\n        return 0;\n    }\n};',
      go: 'func maxArea(height []int) int {\n    // your code here\n    return 0\n}',
      rust: 'impl Solution {\n    pub fn max_area(height: Vec<i32>) -> i32 {\n        // your code here\n        0\n    }\n}',
    },
    hints: [
      { tier: 1, label: 'Conceptual', content: 'The area is limited by the shorter line. Think about how to maximize width × min(height).' },
      { tier: 2, label: 'Approach', content: 'Use two pointers starting from the edges. Move the pointer pointing to the shorter line inward.' },
      { tier: 3, label: 'Pseudocode', content: 'left=0, right=n-1. While left<right: area = min(h[l],h[r])*(r-l). Update max. Move shorter pointer inward.' },
    ],
  },
  {
    id: 'trapping-rain-water',
    title: '6. Trapping Rain Water',
    difficulty: 'Hard',
    tags: ['Array', 'Two Pointers', 'Stack', 'Dynamic Programming'],
    description: 'Given `n` non-negative integers representing an elevation map where the width of each bar is `1`, compute how much water it can trap after raining.',
    examples: [
      { input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' },
      { input: 'height = [4,2,0,3,2,5]', output: '9' },
      { input: 'height = [3,0,2,0,4]', output: '7' },
    ],
    constraints: ['n == height.length', '1 ≤ n ≤ 2 * 10^4', '0 ≤ height[i] ≤ 10^5'],
    templates: {
      python: 'class Solution:\n    def trap(self, height: list[int]) -> int:\n        pass',
      javascript: 'function trap(height) {\n  // your code here\n}',
      typescript: 'function trap(height: number[]): number {\n  // your code here\n}',
      java: 'class Solution {\n    public int trap(int[] height) {\n        // your code here\n        return 0;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    int trap(vector<int>& height) {\n        // your code here\n        return 0;\n    }\n};',
      go: 'func trap(height []int) int {\n    // your code here\n    return 0\n}',
      rust: 'impl Solution {\n    pub fn trap(height: Vec<i32>) -> i32 {\n        // your code here\n        0\n    }\n}',
    },
    hints: [
      { tier: 1, label: 'Conceptual', content: 'Water at each position depends on the max height to its left and right.' },
      { tier: 2, label: 'Approach', content: 'Use two pointers from both ends. Track left_max and right_max. Water at position = min(left_max, right_max) - height[i].' },
      { tier: 3, label: 'Pseudocode', content: 'l=0,r=n-1,lmax=rmax=0. While l<r: if h[l]<h[r]: lmax=max(lmax,h[l]), water+=lmax-h[l], l++. Else: similar from right.' },
    ],
  },
  {
    id: 'word-break',
    title: '7. Word Break',
    difficulty: 'Medium',
    tags: ['Dynamic Programming', 'Hash Table', 'String'],
    description: 'Given a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words.\n\n**Note** that the same word in the dictionary may be reused multiple times in the segmentation.',
    examples: [
      { input: 's = "leetcode", wordDict = ["leet","code"]', output: 'true', explanation: 'Return true because "leetcode" can be segmented as "leet code".' },
      { input: 's = "applepenapple", wordDict = ["apple","pen"]', output: 'true', explanation: 'Return true because "applepenapple" can be segmented as "apple pen apple".' },
      { input: 's = "catsandog", wordDict = ["cats","dog","sand","and","cat"]', output: 'false' },
    ],
    constraints: ['1 ≤ s.length ≤ 300', '1 ≤ wordDict.length ≤ 1000', '1 ≤ wordDict[i].length ≤ 20', 's and wordDict[i] consist of only lowercase English letters.', 'All the strings of wordDict are unique.'],
    templates: {
      python: 'class Solution:\n    def wordBreak(self, s: str, wordDict: list[str]) -> bool:\n        pass',
      javascript: 'function wordBreak(s, wordDict) {\n  // your code here\n}',
      typescript: 'function wordBreak(s: string, wordDict: string[]): boolean {\n  // your code here\n}',
      java: 'class Solution {\n    public boolean wordBreak(String s, java.util.List<String> wordDict) {\n        // your code here\n        return false;\n    }\n}',
      cpp: 'class Solution {\npublic:\n    bool wordBreak(string s, vector<string>& wordDict) {\n        // your code here\n        return false;\n    }\n};',
      go: 'func wordBreak(s string, wordDict []string) bool {\n    // your code here\n    return false\n}',
      rust: 'impl Solution {\n    pub fn word_break(s: String, word_dict: Vec<String>) -> bool {\n        // your code here\n        false\n    }\n}',
    },
    hints: [
      { tier: 1, label: 'Conceptual', content: 'Think about breaking the problem into subproblems: can each prefix of s be segmented?' },
      { tier: 2, label: 'Approach', content: 'Use dynamic programming. dp[i] = true if s[0..i] can be segmented using the dictionary.' },
      { tier: 3, label: 'Pseudocode', content: 'dp[0]=true. For i=1..n: for j=0..i: if dp[j] and s[j..i] in wordDict: dp[i]=true. Return dp[n].' },
    ],
  },
  {
    id: 'merge-intervals',
    title: '8. Merge Intervals',
    difficulty: 'Medium',
    tags: ['Array', 'Sorting'],
    description: 'Given an array of `intervals` where `intervals[i] = [start_i, end_i]`, merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.',
    examples: [
      { input: 'intervals = [[1,3],[2,6],[8,10],[15,18]]', output: '[[1,6],[8,10],[15,18]]', explanation: 'Since intervals [1,3] and [2,6] overlap, merge them into [1,6].' },
      { input: 'intervals = [[1,4],[4,5]]', output: '[[1,5]]', explanation: 'Intervals [1,4] and [4,5] are considered overlapping.' },
    ],
    constraints: ['1 ≤ intervals.length ≤ 10^4', 'intervals[i].length == 2', '0 ≤ start_i ≤ end_i ≤ 10^4'],
    templates: {
      python: 'class Solution:\n    def merge(self, intervals: list[list[int]]) -> list[list[int]]:\n        pass',
      javascript: 'function merge(intervals) {\n  // your code here\n}',
      typescript: 'function merge(intervals: number[][]): number[][] {\n  // your code here\n}',
      java: 'class Solution {\n    public int[][] merge(int[][] intervals) {\n        // your code here\n        return new int[][]{};\n    }\n}',
      cpp: 'class Solution {\npublic:\n    vector<vector<int>> merge(vector<vector<int>>& intervals) {\n        // your code here\n        return {};\n    }\n};',
      go: 'func merge(intervals [][]int) [][]int {\n    // your code here\n    return nil\n}',
      rust: 'impl Solution {\n    pub fn merge(intervals: Vec<Vec<i32>>) -> Vec<Vec<i32>> {\n        // your code here\n        vec![]\n    }\n}',
    },
    hints: [
      { tier: 1, label: 'Conceptual', content: 'Sorting the intervals by start time makes it easier to find overlaps.' },
      { tier: 2, label: 'Approach', content: 'After sorting, iterate and compare the current interval with the last merged one.' },
      { tier: 3, label: 'Pseudocode', content: 'Sort by start. For each interval: if result is empty or no overlap, append. Else merge by extending end = max(end, interval.end).' },
    ],
  },
];
